# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Academic"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://fzhang.com/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-136285585-1"

# Enable comments by entering your Disqus shortname
disqusShortname = "fzhangphd"

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

name = "custom"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

[params]
  # Some other stuff...

  email = "fanzhang@broadinstitute.org"
  address = "77 Avenue Louis PasteurBoston, MA 02115"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""
  twitter = "FanZhang_Jessie"

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:fanzhang@broadinstitute.org"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "https://twitter.com/FanZhang_Jessie"

 # [[params.social]]
 #   icon = "google-scholar"
 #   icon_pack = "ai"
 #   link = "https://scholar.google.com/citations?user=6uF4Sa8AAAAJ&hl=en"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/fzhangcode"

 [params.talks]
    # Show talk time?
    time = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "#cv"
  weight = 7

[[menu.main]]
  name = "Recent Talks"
  url = "#talks"
  weight = 7

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 8

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
