# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).


# Title of your site
title = "Dr. Fan Zhang in Computational and Systems Biology"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://fzhang.com/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2020"

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = "UA-136591234-1"
googleAnalytics = "UA-136591234-2"

# Enable comments by entering your Disqus shortname
disqusShortname = "fzhang"


# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Theme metadata
name = "custom"

# Is theme light or dark?
light = true

# # Primary
primary = "#328cc1"
primary_light = "#328cc1"
primary_dark = "#DA2536"

# Menu
menu_primary = "#494949"
menu_text = "#fff"
menu_text_active = "#328cc1"
menu_title = "#fff"

# Backgrounds
background = "navy"
home_section_odd = "#fff"
home_section_even = "#f7f7f7"


# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 15  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

[outputs]
  # home = [ "HTML", "CSS", "RSS", "JSON" ]
  # section = [ "HTML", "RSS" ]

    home = [ "HTML", "CSS", "RSS" ]
    section = [ "HTML", "RSS" ]
    taxonomy = [ "HTML", "RSS" ]
    taxonomyTerm = [ "HTML", "RSS" ]


# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

[params]
  # Some other stuff...
  # color_theme = "custom"
  themeVariant = "green"
  font = "default"
  disable_sri = true
  name = "Fan Zhang"
  role = "Computational Biologist"
  organizations = [{name = "Harvard Medical School/Brigham and Women's Hospital"}, {name = "Broad Institute of MIT and Harvard"}]
  gravatar = false
  avatar = "portrait.png"
  # email = "fanzhang@broadinstitute.org"
  # address = "77 Avenue Louis Pasteur, Boston, MA 02115"
  # twitter = "FanZhang_Jessie" 
  # office_hours = ""
  # phone = ""
  # skype = ""
  # telegram = ""

# Enable Keybase in Contact widget by entering your keybase.io username.
  keybase = ""

  logo = ""

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 1
  map_api_key = ""
  latitude = "42.3601"
  longitude = "71.0589"
  zoom = 15


  highlight = true
  highlight_languages = ["bash", "cs", "http", "javascript", "json", "markdown", "r", "xml", "yaml"]
  # highlight_style = "tomorrow-night-eighties"

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []



  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]



# Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"
    time_format = "3:04 PM"

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3


  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:fanzhang@broadinstitute.org"

  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0002-6102-2970"
    
    
#   [[params.social]]
#     icon = "twitter"
#    icon_pack = "fab"
#    link = "https://twitter.com/FanZhang_Jessie"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=yOek_fgAAAAJ&hl=en"
  

#  [[params.social]]
#    icon = "laptop-code"
#    icon_pack = "ai"
#    link = "https://github.com/fzhangcode"

#  [[params.social]]
#    icon = "github"
#     icon_pack = "fab"
#    link = "https://github.com/fzhangcode"
    
#  [[params.social]]
#    icon = "linkedin"
#    icon_pack = "fa"
#    link = "https://www.linkedin.com/in/fan-zhang-phd-2149306b/"



 [[params.talks]]
#    # Show talk time?
    time = true

[[params.menus]]
  # Align the main menu to the right of the page? (true/false)
  align_right = true



[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Recent Talks"
  url = "#talks"
  weight = 3
  
[[menu.main]]
  name = "Projects"
  url = "#project"
  weight = 4
  
[[menu.main]]
  name = "CV"
  url = "#cv"
  weight = 5

  
# [[menu.main]]
#  name = "Experience"
#  url = "#experience"
#  weight = 6
  
  
# [[menu.main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 6

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"


# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"


